"""Expand the existing integer quarter-wave RTL into a synchronous ROM.

No floating point recalculation: every word comes from sine_lut_12bit.v.
Run from any directory; --check verifies the checked-in generated module.
"""
import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/audio/sine_lut_12bit.v"
TARGET = ROOT / "src/audio/sine_rom_12bit_sync.v"


def render():
    entries = re.findall(r"7'd(\d+)\s*:\s*mag\s*=\s*11'd\s*(\d+)\s*;", SOURCE.read_text(encoding="utf-8"))
    table = {int(k): int(v) for k, v in entries}
    if len(entries) != 65 or set(table) != set(range(65)):
        raise ValueError("Expected exactly 65 quarter-wave entries")
    words = []
    for addr in range(256):
        quad, index = divmod(addr, 64)
        k = 64 - index if quad & 1 else index
        words.append(2048 - table[k] if quad & 2 else 2048 + table[k])
    assert [words[i] for i in (0, 64, 128, 192)] == [2048, 3840, 2048, 256]
    assert min(words) == 256 and max(words) == 3840
    assignments = "\n".join(f"            8'd{i}: sine_code <= 12'h{v:03X};" for i, v in enumerate(words))
    return """// Generated by tools/gen-dds-sine-rom.py from sine_lut_12bit.v.
// Full-period integer values, one-clock synchronous read, no reset/enable.
// DDS resets its external output and prefetches phase zero on a note change.
// XST ROM_STYLE requests block ROM; actual mapping must be checked in MAP.
(* rom_style = "block" *) module sine_rom_12bit_sync (
    input wire clk,
    input wire [7:0] phase_addr,
    output reg [11:0] sine_code
);
    always @(posedge clk) begin
        case (phase_addr)
""" + assignments + """
            default: sine_code <= 12'h800;
        endcase
    end
endmodule
"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        if TARGET.read_text(encoding="utf-8") != expected:
            raise SystemExit("FAIL: generated sine ROM is out of date")
        print("PASS: 256 integer sine ROM words match the generator")
    else:
        TARGET.write_text(expected, encoding="utf-8", newline="\n")
        print(f"Wrote {TARGET}")
