#=============================================================================
# Helpers for producing a HUMAN-VIEW ISE Project Navigator project on the VM.
#
# This is NOT part of the frozen command set: `ise.ps1` keeps its twelve commands
# and remains the single source of truth for builds/simulation/programming. These
# helpers exist so a human can open the design in the ISE 14.7 GUI and read it.
#
# Encoding: the repository keeps UTF-8 (what git, XST and the toolchain use). The
# VM viewer copy is written in the Windows ANSI code page (936 / GBK) because the
# ISE 14.7 HDL editor opens files as ANSI on a Chinese Windows, which turns UTF-8
# Chinese comments into mojibake. Only the copy is converted - never the repo.
#
# All text here is ASCII (the generated .tcl/.cmd must stay ASCII: CMD reads
# non-ASCII .cmd files as GBK and would corrupt them).
#=============================================================================

# Device string (e.g. xc3s50an-4-tqg144) -> the four values the ISE Tcl API wants.
function Get-IseGuiDeviceFacts {
    param([Parameter(Mandatory)][string]$DeviceString)
    if ($DeviceString -notmatch '^(?<part>xc[a-z0-9]+)-(?<speed>[1-9][0-9]*[a-z]?)-(?<package>[a-z]+[0-9]+)$') {
        throw "Cannot parse device string: $DeviceString"
    }
    $part = $Matches['part']
    $speed = '-' + $Matches['speed']
    $package = $Matches['package']
    # Family names are the ones ISE 14.7 itself reports (measured: an XC3S50AN
    # project says "Spartan3A and Spartan3AN"). Anything unknown must be passed
    # explicitly instead of being guessed.
    $family = $null
    if ($part -match '^xc3s\d+an$' -or $part -match '^xc3s\d+a$') { $family = 'Spartan3A and Spartan3AN' }
    elseif ($part -match '^xc3s\d+e$') { $family = 'Spartan3E' }
    elseif ($part -match '^xc3s\d+$') { $family = 'Spartan3' }
    elseif ($part -match '^xc6s') { $family = 'Spartan6' }
    return [pscustomobject]@{ Part = $part; Package = $package; Speed = $speed; Family = $family }
}

# Extensions treated as text. Everything else is copied byte for byte.
$script:GuiTextExtensions = @('.v', '.vh', '.sv', '.svh', '.ucf', '.xdc', '.tcl', '.cmd', '.txt', '.md', '.coe', '.hex')

function Test-GuiTextFile {
    param([Parameter(Mandatory)][string]$Path)
    return ($script:GuiTextExtensions -contains ([IO.Path]::GetExtension($Path).ToLowerInvariant()))
}

# UTF-8 -> ANSI(code page) for the VM copy.
function ConvertTo-AnsiFile {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Destination,
        [int]$CodePage = 936
    )
    $text = [IO.File]::ReadAllText($Path, [Text.Encoding]::UTF8)
    $enc = [Text.Encoding]::GetEncoding($CodePage)
    $parent = Split-Path -Parent $Destination
    if ($parent) { New-Item -ItemType Directory -Force -Path $parent | Out-Null }
    [IO.File]::WriteAllText($Destination, $text, $enc)
    return $text.Length
}

# ANSI(code page) -> UTF-8, for bringing edits made in the ISE editor back.
function ConvertFrom-AnsiFile {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$Destination,
        [int]$CodePage = 936
    )
    $enc = [Text.Encoding]::GetEncoding($CodePage)
    $text = [IO.File]::ReadAllText($Path, $enc)
    $parent = Split-Path -Parent $Destination
    if ($parent) { New-Item -ItemType Directory -Force -Path $parent | Out-Null }
    [IO.File]::WriteAllText($Destination, $text, [Text.UTF8Encoding]::new($false))
    return $text.Length
}

# The Tcl program that creates the .xise through ISE's own project API.
function New-GuiProjectTcl {
    param(
        [Parameter(Mandatory)][string]$XiseFileName,
        [Parameter(Mandatory)][string]$Family,
        [Parameter(Mandatory)][string]$Part,
        [Parameter(Mandatory)][string]$Package,
        [Parameter(Mandatory)][string]$Speed,
        [Parameter(Mandatory)][string[]]$SynthesisFiles,
        [Parameter(Mandatory)][string[]]$Testbenches,
        [AllowNull()][string]$Top = $null,
        [AllowNull()][string]$IncludeDir = $null
    )
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add('# generated by tools/make-gui-project.ps1 - human-view project copy')
    $lines.Add('set here [file normalize [pwd]]')
    $lines.Add(('set proj [file join $here ' + $XiseFileName + ']'))
    # Regenerating must work without a manual cleanup: `project new` refuses to
    # overwrite an existing project file (measured: project_087).
    $lines.Add('if {[file exists $proj]} { file delete -force $proj }')
    $lines.Add('project new $proj')
    $lines.Add(('project set family {' + $Family + '}'))
    $lines.Add(('project set device ' + $Part))
    # The Pb-free package spelling differs between ISE builds, so try the plain name
    # first and fall back rather than hard-coding one.
    $plain = $Package -replace 'g(\d+)$', '$1'
    $lines.Add(('if {[catch {project set package ' + $plain + '} msg]} {'))
    $lines.Add(('    project set package ' + $Package))
    $lines.Add('}')
    $lines.Add(('if {[catch {project set speed ' + $Speed + '} msg]} { puts "speed rejected: $msg" }'))
    foreach ($f in $SynthesisFiles) { $lines.Add(('if {[catch {xfile add ' + $f + '} msg]} { puts "WARN: ' + $f + ' : $msg" }')) }
    foreach ($f in $Testbenches) {
        $lines.Add(('if {[catch {xfile add ' + $f + ' -view Simulation} msg]} { if {[catch {xfile add ' + $f + '} msg2]} { puts "WARN: ' + $f + ' : $msg2" } }'))
    }
    if ($IncludeDir) {
        $lines.Add(('if {[catch {project set "Verilog Include Directories" "' + $IncludeDir + '"} msg]} { puts "NOTE: include dirs: $msg" }'))
    }
    if ($Top) {
        $lines.Add(('if {[catch {project set "Top-Level Module" ' + $Top + '} msg]} { puts "NOTE: top module: $msg" }'))
    }
    $lines.Add('project close')
    $lines.Add('puts "PROJECT_FILE: $proj"')
    $lines.Add('puts "PROJECT_EXISTS: [file exists $proj]"')
    return ($lines.ToArray() -join "`r`n") + "`r`n"
}

function New-GuiProjectRunner {
    param([Parameter(Mandatory)][string]$TclName)
    return (@(
        '@echo off'
        'setlocal'
        'cd /d "%~dp0"'
        'del /q make.out 2>nul'
        ('call "' + $script:Settings + '" > env_xtclsh.log 2>&1')
        ('xtclsh ' + $TclName + ' > make.out 2>&1')
        'echo RC=%ERRORLEVEL% >> make.out'
    ) -join "`r`n") + "`r`n"
}
